<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Receipt</title>
</head>
<body style="margin:0; padding:24px; background:#f7f3ea; font-family:Arial, sans-serif; color:#17322c;">
    <div style="max-width:680px; margin:0 auto; background:#ffffff; border-radius:20px; padding:32px; border:1px solid #e8decb;">
        <p style="margin:0 0 8px; font-size:12px; letter-spacing:0.18em; text-transform:uppercase; color:#b18a3d;">
            HYVE Workspace
        </p>

        <h1 style="margin:0 0 10px; font-size:28px; line-height:1.2;">
            Payment receipt
        </h1>

        <p style="margin:0 0 20px; font-size:16px; line-height:1.7; color:#50635e;">
            Hi {{ $context['customer_name'] }}, we received your payment and your booking is now fully paid.
        </p>

        <div style="margin:0 0 24px; padding:18px 20px; border-radius:16px; background:#edf6df;">
            <div style="font-size:12px; text-transform:uppercase; letter-spacing:0.12em; color:#6d7f77; margin-bottom:6px;">Reference number</div>
            <div style="font-size:24px; font-weight:700;">{{ $context['reference_no'] }}</div>
        </div>

        <table role="presentation" style="width:100%; border-collapse:collapse; margin-bottom:24px;">
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Customer</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">{{ $context['customer_name'] }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Payment method</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">{{ $context['payment_method'] }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Payment recorded</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">{{ $context['paid_at'] }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Amount received</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">Php {{ number_format((float) $context['payment_amount'], 2) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Gross total</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">Php {{ number_format((float) $context['gross_total_amount'], 2) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Discount</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">
                    @if ((float) ($context['discount_amount'] ?? 0) > 0)
                        {{ $context['discount_label'] }} - Php {{ number_format((float) $context['discount_amount'], 2) }}
                    @else
                        No discount
                    @endif
                </td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Final payable total</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">Php {{ number_format((float) $context['payable_total_amount'], 2) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Paid so far</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">Php {{ number_format((float) $context['downpayment_amount'], 2) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0; color:#6d7f77;">Remaining balance</td>
                <td style="padding:8px 0; text-align:right; font-weight:700;">Php {{ number_format((float) $context['balance_amount'], 2) }}</td>
            </tr>
        </table>

        @if (! empty($context['lines']))
            <div style="margin-bottom:24px;">
                <div style="font-size:18px; font-weight:700; margin-bottom:12px;">Booking details</div>

                @foreach ($context['lines'] as $line)
                    <div style="padding:14px 16px; border:1px solid #e8decb; border-radius:14px; margin-bottom:10px;">
                        <div style="font-size:16px; font-weight:700; margin-bottom:4px;">{{ $line['room_name'] ?? $line['room'] ?? 'Room' }}</div>
                        <div style="font-size:14px; color:#50635e;">{{ $line['date'] }} | {{ $line['time'] }}</div>
                    </div>
                @endforeach
            </div>
        @endif

        <p style="margin:0; font-size:14px; line-height:1.7; color:#50635e;">
            This is an unofficial receipt generated by HYVE for payment confirmation. Please keep this email for your records.
        </p>
    </div>
</body>
</html>
